jobs:
  - script: >
      multibranchPipelineJob('example') {
        branchSources {
            git {
                id('12121212') // IMPORTANT: use a constant and unique identifier
                remote('git@github.com:matijasx/example_webapp.git')
                credentialsId('ssh_git_key_matiss')
                includes('*')
            }
        }
      }