jenkins:
# Setting initial admin  
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: ${admin}

# Adding ssh key to pull repositories
credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: ssh_git_key_matiss
              username: ssh_root
              passphrase: ''
              description: "SSH passphrase with private key file. Private key provided"
              privateKeySource:
                directEntry:
                  privateKey: ${git_ssh_key}

# Adding stdPipeline library
unclassified:
  globalLibraries:
    libraries:
      - name: "stdPipeline"
        defaultVersion: "master"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "git@github.com:matijasx/jenkins_lib.git"
                credentialsId: "ssh_git_key_matiss"